### ISSUE TITLE
RabbitMQ queues and scheduled tasks

### ISSUE THREAD

**Issue by JannKleen** [jezdez/hirefire#11]
This might be more of an implementation question than a bug report.

We have lots of scheduled tasks (a few thousand) and wanted to scale our workers using HireFire.
The problem is that scheduled tasks using RabbitMQ and Celery are implemented by the worker fetching the tasks but not ACK'ing them. This removes them from the queue and saves them on the worker until it's time to execute them, or the worker dies.

What happens: The workers fetch the scheduled tasks and reduce the queue length ... this scales down the number of workers, which frees up the scheduled tasks, which scales up workers ... start from the beginning.

The only way I could imagine solving this is to create two queues (one for scheduled tasks and one for 'immediate' tasks) and only scale based on the latter one. If this is actually the only solution, we might want to add it to the docs as a recipe.

**Comment by ryanhiebert** [comment]
You might look at #13, which I think could help with this. In particular, I'd like some feedback on what statuses (of `active`, `scheduled`, and `reserved`) should be default, and what should be allowed as far as configuration.

**Comment by JannKleen** [comment]
@ryanhiebert Our current approach is to split our queue into two ("celery" and "scheduled") and only consider the "celery" queue for scaling

**Comment by ryanhiebert** [comment]
@JannKleen: Yes, that's a pretty good approach if it's a reasonable for you. The work in #13 may allow you to use HireFire on those `scheduled `dynos too.

**Comment by JannKleen** [comment]
@ryanhiebert sounds great! One small correction, our dynos scale on ```celery``` queue length but work on both queues

**Comment by ryanhiebert** [comment]
@JannKleen: Should this issue be closed now?

**Comment by JannKleen** [comment]
Yes, thanks!
