### ISSUE TITLE
install hirefire raises syntax error

### ISSUE THREAD

**Issue by t-io** [jezdez/hirefire#24]
hirefire can be installed successfully but raises a syntax error
When installing 0.0.4 with pip I get:
`File "/tmp/pip_build_root/HireFire/hirefire/procs/hotqueue.py", line 59`
__SyntaxError: invalid syntax__ -> `def quantity(self. **kwargs):`
This typo is also in the latest master

**Comment by ryanhiebert** [comment]
Indeed. I guess that means nobody (except you now) is using hotqueue. Thanks for the bug report!

You can either 1) wait for someone to fix this bug (perhaps me later this evening), or 2) create a pull request with the fix. Once that's done, I can't give you a timeframe on when a release would be cut (it's not up to me), but you can install the updated branch directly from git with pip.

**Comment by t-io** [comment]
It's not critical for me, I don't use hotqueue in my project. I just stumble across this ugly syntax error installing hirefire via pip.  👉 PR#25
